# -*- coding: utf-8 -*-
"""Classification Hands-on.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FB9sLSY1KbTQsCvqwvyxJSrx0vfsbFyU
"""

# Python program to perform classification on Iris dataset
 
# Run this program on your local Python interpreter
# provided you have installed the required libraries
 
# Importing the required libraries

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import datasets
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()
x = iris.data
y = iris.target

# splitting X and y into training and testing sets
x_test, x_train, y_test, y_train = train_test_split(x, y, test_size=0.2, random_state=1)

# GAUSSIAN NAIVE BAYES
gnb = GaussianNB()

# train the model
gnb.fit(x_train, y_train)

# make predictions
gnb_pred = gnb.predict(x_test)

# print the accuracy
print('Accuracy of Gaussian Naive Bayes: ', accuracy_score(y_test, gnb_pred))

# DECISION TREE CLASSIFIER
dt = DecisionTreeClassifier(random_state=0)

# train the model
dt.fit(x_train, y_train)

# make predictions
dt_pred = dt.predict(x_test)

# print the accuracy
print("Accuracy of Decision Tree Classifier: ", accuracy_score(y_test, dt_pred))

# SUPPORT VECTOR MACHINE
svm_clf = svm.SVC(kernel='linear')

# train the model
svm_clf.fit(x_train, y_train)

# make prediction
svm_pred = svm_clf.predict(x_test)

# print the accuracy
print("Accuracy of Support Vector Machine: ", accuracy_score(y_test, svm_pred))